Problem: missing support NFT(#14)
crypto-org-chain/chainlibpy pull request #16
Opened 2021-07-29 07:42 UTC by linfeng-crypto

2021-07-30 02:53 UTC, tomtau commented
should it also update the changelog?

2021-07-30 06:47 UTC, linfeng-crypto commented
> should it also update the changelog?

update the changelog when publishing a new version?

2021-08-05 08:35 UTC, tomtau requested changes
> update the changelog when publishing a new version?
not sure of the release process here -- would that be in a separate PR?

https://github.com/crypto-org-chain/chainlibpy/pull/16#issuecomment-888915697

2021-08-05 08:35 UTC, tomtau commented on chainlibpy/transaction.py
> +        print(list(message_bytes))
is this needed? or can use some debug log level, so one can turn it off?

2021-08-06 06:56 UTC, merged